/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUcadastrarEpis;
import java.awt.Color;

/**
 *
 * @author josue
 */
public class FormEpisodio extends javax.swing.JFrame implements Form{

    /**
     * Creates new form FormEpisodio2
     */
    private FormMain form;
    
    private String id;
    private String numEP;
    private String idserie;
    private String temporada;
    private String titulo;
    private String resumo;
    private CDUcadastrarEpis cduce;
    public FormEpisodio(FormMain formMain) {
        initComponents();
        this.form=formMain;
    }
    
    public void setcdu(CDUcadastrarEpis cduce){
        this.cduce = cduce;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadEp_LB = new javax.swing.JLabel();
        ser_LB = new javax.swing.JLabel();
        inf_Serie = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Ep_LB = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        dados_EP = new java.awt.Panel();
        id_ep_LB = new javax.swing.JLabel();
        id_ep_TF = new javax.swing.JTextField();
        N_ep_LB = new javax.swing.JLabel();
        N_ep_TF = new javax.swing.JTextField();
        Temp_ep_LB = new javax.swing.JLabel();
        Temp_ep_TF = new javax.swing.JTextField();
        Tit_ep_LB = new javax.swing.JLabel();
        Tit_ep_TF = new javax.swing.JTextField();
        Res_ep_LB = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setName("JFrameEpisodio"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 650));

        cadEp_LB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cadEp_LB.setText("CADASTRANDO EPISÓDIOS");
        cadEp_LB.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        ser_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ser_LB.setLabelFor(inf_Serie);
        ser_LB.setText("Serie (id):");

        inf_Serie.setForeground(new java.awt.Color(153, 153, 153));
        inf_Serie.setText("Inf. id Série:");
        inf_Serie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inf_SerieMouseClicked(evt);
            }
        });
        inf_Serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inf_SerieActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");

        Ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ep_LB.setText("Episódio:");

        id_ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_ep_LB.setText("ID:");

        N_ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        N_ep_LB.setLabelFor(N_ep_TF);
        N_ep_LB.setText("Nº do Episódio:");

        Temp_ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Temp_ep_LB.setText("Temporada:");

        Tit_ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Tit_ep_LB.setText("Título:");

        Res_ep_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Res_ep_LB.setText("Resumo:");

        javax.swing.GroupLayout dados_EPLayout = new javax.swing.GroupLayout(dados_EP);
        dados_EP.setLayout(dados_EPLayout);
        dados_EPLayout.setHorizontalGroup(
            dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_EPLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Temp_ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Temp_ep_TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(id_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(id_ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_EPLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(N_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(N_ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tit_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tit_ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128))
                    .addGroup(dados_EPLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Res_ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        dados_EPLayout.setVerticalGroup(
            dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_EPLayout.createSequentialGroup()
                .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dados_EPLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(id_ep_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dados_EPLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(N_ep_LB)
                            .addComponent(Tit_ep_LB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tit_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(N_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(dados_EPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dados_EPLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(Temp_ep_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Temp_ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dados_EPLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(Res_ep_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inf_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ser_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cadEp_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(258, 258, 258))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Ep_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(368, 368, 368))))
            .addComponent(jSeparator2)
            .addComponent(jSeparator1)
            .addComponent(dados_EP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cadEp_LB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ser_LB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inf_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(17, 17, 17)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ep_LB)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dados_EP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inf_SerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inf_SerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inf_SerieActionPerformed

    private void inf_SerieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inf_SerieMouseClicked
        // TODO add your handling code here:
        inf_Serie.setText("");
        inf_Serie.setForeground(Color.BLACK);
    }//GEN-LAST:event_inf_SerieMouseClicked

    /**
     * @param args the command line arguments
     */


    @Override
    public void exibe() {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEpisodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEpisodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEpisodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEpisodio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEpisodio(form).setVisible(true);
                form.setVisible(false);
            }
        });
         
    }
    
    public String getid() { return id;};
    public String getnumEP(){return numEP;};
    public String getidserie() { return idserie;}
    public String gettemporada() { return temporada;}
    public String gettitulo() { return titulo;}
    public String getresumo() { return resumo; }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ep_LB;
    private javax.swing.JLabel N_ep_LB;
    private javax.swing.JTextField N_ep_TF;
    private javax.swing.JLabel Res_ep_LB;
    private javax.swing.JLabel Temp_ep_LB;
    private javax.swing.JTextField Temp_ep_TF;
    private javax.swing.JLabel Tit_ep_LB;
    private javax.swing.JTextField Tit_ep_TF;
    private javax.swing.JLabel cadEp_LB;
    private java.awt.Panel dados_EP;
    private javax.swing.JLabel id_ep_LB;
    private javax.swing.JTextField id_ep_TF;
    private javax.swing.JTextField inf_Serie;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel ser_LB;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
