/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;

import CDU.CDUcadastrarAtor;
import java.awt.Color;

/**
 *
 * @author josue
 */
public class FormAtor extends javax.swing.JFrame implements Form {

    private String id;
    private String nome;
    private String nacionalidade;
    private String performance;

    FormPerformance formPf;

    private CDUcadastrarAtor cduca;

    public void setcdu(CDUcadastrarAtor cduca) {
        this.cduca = cduca;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cad_ator_LB = new javax.swing.JLabel();
        id_LB = new javax.swing.JLabel();
        id_TF = new javax.swing.JTextField();
        nome_LB = new javax.swing.JLabel();
        nome_TF = new javax.swing.JTextField();
        nacion_LB = new javax.swing.JLabel();
        nacion_TF = new javax.swing.JTextField();
        salvar_btn = new javax.swing.JButton();
        atualizar_btn = new javax.swing.JButton();
        deletar_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Ator");
        setMinimumSize(new java.awt.Dimension(950, 650));
        setName("FrameAtor"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 650));

        Cad_ator_LB.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Cad_ator_LB.setForeground(new java.awt.Color(255, 0, 51));
        Cad_ator_LB.setText("CADASTRANDO UM ATOR:");

        id_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_LB.setForeground(new java.awt.Color(255, 0, 51));
        id_LB.setText("ID:");

        nome_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nome_LB.setForeground(new java.awt.Color(255, 0, 51));
        nome_LB.setText("Nome do Ator:");

        nacion_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nacion_LB.setForeground(new java.awt.Color(255, 0, 51));
        nacion_LB.setText("Nacionalidade:");

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvar_btn.setForeground(new java.awt.Color(255, 0, 0));
        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        atualizar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizar_btn.setForeground(new java.awt.Color(255, 0, 0));
        atualizar_btn.setText("Editar");
        atualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_btnActionPerformed(evt);
            }
        });

        deletar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletar_btn.setForeground(new java.awt.Color(255, 0, 0));
        deletar_btn.setText("Deletar");
        deletar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_btnActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID:", "Nome:", "Nacionalidade:"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(Cad_ator_LB)
                .addGap(299, 299, 299))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletar_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome_LB)))
                    .addComponent(nacion_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacion_TF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Cad_ator_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_LB)
                            .addComponent(nome_LB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(nacion_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nacion_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_btn)
                            .addComponent(atualizar_btn)
                            .addComponent(deletar_btn)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("JframeAtor");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvar_btnActionPerformed
        // TODO add your handling code here:
        id = id_TF.getText();
        nome = nome_TF.getText();
        nacionalidade = nacion_TF.getText();

        cduca.salvarAtor();
    }// GEN-LAST:event_salvar_btnActionPerformed

    private void deletar_btnActionPerformed(java.awt.event.ActionEvent evt) {
        id = id_TF.getText();
        nome = nome_TF.getText();
        nacionalidade = nacion_TF.getText();
        cduca.deletarAtor();
    }

    private void atualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {
        id = id_TF.getText();
        nome = nome_TF.getText();
        nacionalidade = nacion_TF.getText();

        cduca.atualizarAtor();
    }

    private void listar_btnActionPerformed(java.awt.event.ActionEvent evt) {
        id = id_TF.getText();
        nome = nome_TF.getText();
        nacionalidade = nacion_TF.getText();

        // cduca.listarAtor();
    }

    /**
     * @param args the command line arguments
     */

    @Override
    public void exibe() {

        initComponents();
        getContentPane().setBackground(Color.BLACK);
        this.setVisible(true);

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAtor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAtor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAtor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAtor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAtor().setVisible(true);
            }
        });

    }

    /**
     * Metodo para retorno do Id
     * 
     * @return <Strong>String</Strong> id
     */
    public String getId() {
        return id;
    }

    /**
     * Metodo para retorno do Nome
     * 
     * @return <Strong>String</Strong> nome
     */
    public String getNome() {
        return nome;
    }

    /**
     * Metodo para retorno da Nacionalidade
     * 
     * @return <Strong>String</Strong> nacionalidade
     */
    public String getNacionalidade() {
        return nacionalidade;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cad_ator_LB;
    private javax.swing.JButton atualizar_btn;
    private javax.swing.JButton deletar_btn;
    private javax.swing.JLabel id_LB;
    private javax.swing.JTextField id_TF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nacion_LB;
    private javax.swing.JTextField nacion_TF;
    private javax.swing.JLabel nome_LB;
    private javax.swing.JTextField nome_TF;
    private javax.swing.JButton salvar_btn;
    // End of variables declaration//GEN-END:variables
}
