/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUcadastrarPers;
import java.awt.Color;
import javax.swing.JOptionPane;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author josue
 * @since 2.1
 *        Creates new form FormPersonagem
 * 
 */
public class FormPersonagem extends javax.swing.JFrame implements Form {

    /** Id do personagem */
    private int idPs;
    /** Nome do personagem */
    private String nomePs;
    /** Controlado de caso de uso do personagem */
    private CDUcadastrarPers cdups;

    /**
     * Diz ao formulario qual o seu controlador de caso de uso
     * 
     * @param CDUcadastrarPers cdups
     */
    public void setPers(CDUcadastrarPers cdups) {
        this.cdups = cdups;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        nome_pers_LB = new javax.swing.JLabel();
        nome_pers_TF = new javax.swing.JTextField();
        id_pers_LB = new javax.swing.JLabel();
        id_pers_TF = new javax.swing.JTextField();
        salvar_btn = new javax.swing.JButton();
        barra_rolagem = new javax.swing.JScrollPane();
        list_exibe = new javax.swing.JTable();
        atualizar_btn = new javax.swing.JButton();
        deletar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        setPreferredSize(new java.awt.Dimension(950, 650));

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 0, 0));
        Titulo.setText("Cadastrando Personagens:");

        nome_pers_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nome_pers_LB.setForeground(new java.awt.Color(255, 0, 0));
        nome_pers_LB.setText("ID:");

        id_pers_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_pers_LB.setForeground(new java.awt.Color(255, 0, 0));
        id_pers_LB.setText("Nome do Personagem:");

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvar_btn.setForeground(new java.awt.Color(255, 0, 0));
        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        list_exibe.setAutoCreateRowSorter(true);
        list_exibe.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        list_exibe.setForeground(new java.awt.Color(255, 0, 0));
        list_exibe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nome do Personagem"
            }
        ));
        barra_rolagem.setViewportView(list_exibe);

        atualizar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizar_btn.setForeground(new java.awt.Color(255, 0, 0));
        atualizar_btn.setText("Editar");
        atualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_btnActionPerformed(evt);
            }
        });

        deletar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletar_btn.setForeground(new java.awt.Color(255, 0, 0));
        deletar_btn.setText("Deletar");
        deletar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_pers_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_pers_LB)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_pers_LB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome_pers_LB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_btn)
                            .addComponent(atualizar_btn)
                            .addComponent(deletar_btn))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Açao do botao de salvar os dados no banco de dados */
    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_salvar_btnActionPerformed
        // TODO add your handling code here:
        nomePs = nome_pers_TF.getText();
        idPs = Integer.parseInt(id_pers_TF.getText());

        cdups.salvarPersonagem();
        JOptionPane.showMessageDialog(null, "Personagem:" + nomePs + " Salvo com sucesso");
        
        limpacampos();

    }// GEN-LAST:event_salvar_btnActionPerformed

    // CRIAR BOTOES DE ATUALIZAR E DELETAR

    private void atualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO
        nomePs = nome_pers_TF.getText();
        idPs = Integer.parseInt(id_pers_TF.getText());
        cdups.atualizarPersonagem();
        limpacampos();

    }

    private void deletar_btnActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO
        nomePs = nome_pers_TF.getText();
        idPs = Integer.parseInt(id_pers_TF.getText());
        cdups.deletarPersonagem();
        limpacampos();
    }
    
    public void limpacampos(){
        
        nome_pers_TF.setText("");
        id_pers_TF.setText("");  
        
    }

    /**
     * @param args the command line arguments
     * @Jlabel Titulo ;id_pers_LB ; nome_pers_LB
     * @JTextField id_pers_TF; nome_pers_TF
     * @JButton salvar_btn
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton atualizar_btn;
    private javax.swing.JScrollPane barra_rolagem;
    private javax.swing.JButton deletar_btn;
    private javax.swing.JLabel id_pers_LB;
    private javax.swing.JTextField id_pers_TF;
    private javax.swing.JTable list_exibe;
    private javax.swing.JLabel nome_pers_LB;
    private javax.swing.JTextField nome_pers_TF;
    private javax.swing.JButton salvar_btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void exibe() {

        initComponents();
        getContentPane().setBackground(Color.BLACK);
        this.setVisible(true);

        // list_exibe = new JTable(dados,colunas);
        // barra_rolagem = new JScrollPane(list_exibe);

    }

    public int getId() {
        return idPs;
    }

    public String getNome() {
        return nomePs;
    }
}
