/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUcadastrarPers;
import java.awt.Color;

/**
 *
 * @author josue
 */
public class FormPersonagem extends javax.swing.JFrame implements Form{

    /**
     * Creates new form FormPersonagem
     */
	private int idPs;
	private String nomePs;
        private CDUcadastrarPers cdups; // caso de uso personagem
        
        public void setPers(CDUcadastrarPers cdups) {
            this.cdups = cdups;
	}

  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        nome_pers_LB = new javax.swing.JLabel();
        nome_pers_TF = new javax.swing.JTextField();
        id_pers_LB = new javax.swing.JLabel();
        id_pers_TF = new javax.swing.JTextField();
        salvar_btn = new javax.swing.JButton();
        barra_rolagem = new javax.swing.JScrollPane();
        list_exibe = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        setPreferredSize(new java.awt.Dimension(950, 650));

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 0, 0));
        Titulo.setText("Cadastrando Personagens:");

        nome_pers_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nome_pers_LB.setForeground(new java.awt.Color(255, 0, 0));
        nome_pers_LB.setText("ID:");

        id_pers_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_pers_LB.setForeground(new java.awt.Color(255, 0, 0));
        id_pers_LB.setText("Nome do Personagem:");

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvar_btn.setForeground(new java.awt.Color(255, 0, 0));
        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        list_exibe.setAutoCreateRowSorter(true);
        list_exibe.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        list_exibe.setForeground(new java.awt.Color(255, 0, 0));
        list_exibe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "Nome do Personagem"
            }
        ));
        barra_rolagem.setViewportView(list_exibe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(salvar_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_pers_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_pers_LB))))
                .addGap(18, 18, 18)
                .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(id_pers_LB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nome_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nome_pers_LB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id_pers_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addComponent(salvar_btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_btnActionPerformed
        // TODO add your handling code here:
        nomePs = nome_pers_TF.getText();
        idPs = Integer.parseInt(id_pers_TF.getText());
        
        cdups.salvarPersonagem();
        
    }//GEN-LAST:event_salvar_btnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane barra_rolagem;
    private javax.swing.JLabel id_pers_LB;
    private javax.swing.JTextField id_pers_TF;
    private javax.swing.JTable list_exibe;
    private javax.swing.JLabel nome_pers_LB;
    private javax.swing.JTextField nome_pers_TF;
    private javax.swing.JButton salvar_btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void exibe() {
        
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        this.setVisible(true);
    }
    
    public int getId() {
	return idPs;
    }

    public String getNome() {
    	return nomePs;
    }
}
