/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUMain;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.Console;
import javax.swing.ImageIcon;

/**
 *
 * @author josue
 */
public class FormMain extends javax.swing.JFrame implements Form {

    private CDUMain cdumain;

    public CDUMain getCdumain() {
        return cdumain;
    }

    public void setcdu(CDUMain cdu) {
        this.cdumain = cdu;
    }

    public void exibe() {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" try catch do Jframe ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }

        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormMain().setVisible(true);
        });

        // String opcao;
        // Console c = System.console();
        // boolean termina = false;

        System.out.println("POOFlix\n");

        // while (!termina) {
        // System.out.println("1. Cadastrar Série\n");
        // System.out.println("2. Cadastrar Episódio\n");
        // System.out.println("3. Cadastrar Personagem\n");
        // System.out.println("4. Cadastrar Ator\n");
        // System.out.println("5. Sair\n");

        // opcao = (String) c.readLine("Digite a opção desejada: ");
        // System.out.println(opcao);

        // termina = opcao.equals("5");

        // if (!termina) {
        // cdumain.processaOpcao(opcao);
        // telaCadastro.setVisible(false);
        // }
        // }
    }

    /**
     * Creates new form formMainTela
     */
    public FormMain() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        cadastra.setVisible(false);
        cdumain = new CDUMain(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_bemVindo = new javax.swing.JLabel();
        btn_red_icon = new javax.swing.JButton();
        btn_green_icon = new javax.swing.JButton();
        btn_yellow_icon = new javax.swing.JButton();
        cadastra = new java.awt.Panel();
        cadSerie1 = new javax.swing.JButton();
        cadEp1 = new javax.swing.JButton();
        cadPerson1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POOFlix");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(950, 650));
        setName("Tela_FormMain"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LB_bemVindo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LB_bemVindo.setForeground(new java.awt.Color(255, 0, 51));
        LB_bemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_bemVindo.setText("POOflix");
        getContentPane().add(LB_bemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        btn_red_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/red_icon.png"))); // NOI18N
        btn_red_icon.setBorderPainted(false);
        btn_red_icon.setDoubleBuffered(true);
        btn_red_icon.setMaximumSize(new java.awt.Dimension(50, 50));
        btn_red_icon.setMinimumSize(new java.awt.Dimension(50, 50));
        btn_red_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_red_iconMouseClicked(evt);
            }
        });
        btn_red_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_red_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_red_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, 150));

        btn_green_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green_icon.png"))); // NOI18N
        btn_green_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_green_iconMouseClicked(evt);
            }
        });
        btn_green_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_green_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_green_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 150, 150));

        btn_yellow_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/yellow_icon.png"))); // NOI18N
        btn_yellow_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yellow_iconMouseClicked(evt);
            }
        });
        btn_yellow_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yellow_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_yellow_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 150, 150));

        cadastra.setBackground(new java.awt.Color(0, 0, 0));

        cadSerie1.setBackground(new java.awt.Color(153, 153, 153));
        cadSerie1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadSerie1.setForeground(new java.awt.Color(255, 255, 255));
        cadSerie1.setText("1. Cadastrar Série");
        cadSerie1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cadSerie1.setContentAreaFilled(false);
        cadSerie1.setFocusPainted(false);
        cadSerie1.setFocusable(false);
        cadSerie1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadSerie1MouseClicked(evt);
            }
        });

        cadEp1.setBackground(new java.awt.Color(153, 153, 153));
        cadEp1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadEp1.setForeground(new java.awt.Color(255, 255, 255));
        cadEp1.setText("2. Cadastrar Episódio");
        cadEp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cadEp1.setContentAreaFilled(false);

        cadPerson1.setBackground(new java.awt.Color(153, 153, 153));
        cadPerson1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cadPerson1.setForeground(new java.awt.Color(255, 255, 255));
        cadPerson1.setText("3. Cadastrar Personagem");
        cadPerson1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        cadPerson1.setContentAreaFilled(false);

        jButton7.setBackground(new java.awt.Color(153, 153, 153));
        jButton7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("4. Cadastrar Ator");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton7.setContentAreaFilled(false);

        jButton8.setBackground(new java.awt.Color(153, 153, 153));
        jButton8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("5. Cadastrar Performance");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton8.setContentAreaFilled(false);

        jButton9.setBackground(new java.awt.Color(153, 153, 153));
        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("6. Sair");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton9.setContentAreaFilled(false);

        javax.swing.GroupLayout cadastraLayout = new javax.swing.GroupLayout(cadastra);
        cadastra.setLayout(cadastraLayout);
        cadastraLayout.setHorizontalGroup(
                cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastraLayout.createSequentialGroup()
                                .addContainerGap(107, Short.MAX_VALUE)
                                .addGroup(cadastraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(cadastraLayout.createSequentialGroup()
                                                .addGroup(cadastraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(cadSerie1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cadPerson1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(cadastraLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cadEp1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(cadastraLayout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 180,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(101, 101, 101))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastraLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 202,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        cadastraLayout.setVerticalGroup(
                cadastraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastraLayout.createSequentialGroup()
                                .addContainerGap(27, Short.MAX_VALUE)
                                .addGroup(cadastraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cadSerie1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cadEp1, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(cadastraLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cadPerson1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)));

        getContentPane().add(cadastra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 600, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_yellow_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_yellow_iconMouseClicked
        btn_red_iconMouseClicked(evt);
    }// GEN-LAST:event_btn_yellow_iconMouseClicked

    private void cadSerie1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cadSerieMouseClicked
        // TODO add your handling code here:
        String op = "1";
        cdumain.processaOpcao(op);
    }// GEN-LAST:event_cadSerieMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButton6ActionPerformed

    private void btn_yellow_iconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_yellow_iconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_yellow_iconActionPerformed

    private void btn_red_iconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_red_iconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_red_iconActionPerformed

    private void btn_green_iconActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_green_iconActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btn_green_iconActionPerformed

    private void btn_red_iconMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_red_iconMouseClicked
        // TODO add your handling code here:
        btn_red_icon.setVisible(false);
        btn_green_icon.setVisible(false);
        btn_yellow_icon.setVisible(false);
        cadastra.setVisible(true);

    }// GEN-LAST:event_btn_red_iconMouseClicked

    private void btn_green_iconMouseClicked(java.awt.event.MouseEvent evt) {
        btn_red_iconMouseClicked(evt);
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_bemVindo;
    private javax.swing.JButton btn_green_icon;
    private javax.swing.JButton btn_red_icon;
    private javax.swing.JButton btn_yellow_icon;
    private javax.swing.JButton cadEp1;
    private javax.swing.JButton cadPerson1;
    private javax.swing.JButton cadSerie1;
    private java.awt.Panel cadastra;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

}
