/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUcadastrarSerie;
import java.awt.Color;

/**
 *
 * @author josue
 */
public class FormSerie extends javax.swing.JFrame implements Form{

    private String id;
    private String titulo;
    private String idademin;
    private CDUcadastrarSerie cducs;

    public void setcdu(CDUcadastrarSerie cducs) {
        this.cducs = cducs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JLabel();
        id_LB = new javax.swing.JLabel();
        id_TF = new javax.swing.JTextField();
        tit_LB = new javax.swing.JLabel();
        tit_TF = new javax.swing.JTextField();
        barra_rolagem = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        salvar_btn = new javax.swing.JButton();
        atualizar_btn = new javax.swing.JButton();
        deletar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POOFlix - Cadastrar Série");
        setMinimumSize(new java.awt.Dimension(950, 650));

        TITULO.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TITULO.setForeground(new java.awt.Color(255, 0, 0));
        TITULO.setText("CADASTRANDO SÉRIE:");

        id_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        id_LB.setForeground(new java.awt.Color(255, 0, 51));
        id_LB.setText("ID:");

        tit_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tit_LB.setForeground(new java.awt.Color(255, 0, 51));
        tit_LB.setText("Título:");

        barra_rolagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 2, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Titulo"
            }
        ));
        barra_rolagem.setViewportView(jTable1);

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvar_btn.setForeground(new java.awt.Color(255, 0, 0));
        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        atualizar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizar_btn.setForeground(new java.awt.Color(255, 0, 0));
        atualizar_btn.setText("Editar");
        atualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_btnActionPerformed(evt);
            }
        });

        deletar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletar_btn.setForeground(new java.awt.Color(255, 0, 0));
        deletar_btn.setText("Deletar");
        deletar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(TITULO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(tit_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletar_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104)
                        .addComponent(tit_LB, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(TITULO)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_LB)
                            .addComponent(tit_LB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tit_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_btn)
                            .addComponent(atualizar_btn)
                            .addComponent(deletar_btn)))
                    .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_btnActionPerformed
        // TODO add your handling code here:
        id=id_TF.getText();
        titulo=tit_TF.getText();
        
        cducs.salvarSerie();
        
    }//GEN-LAST:event_salvar_btnActionPerformed

    private void atualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizar_btnActionPerformed
        // TODO add your handling code here:
        id=id_TF.getText();
        titulo=tit_TF.getText();
    }//GEN-LAST:event_atualizar_btnActionPerformed

    private void deletar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletar_btnActionPerformed
        // TODO add your handling code here:
        id=id_TF.getText();
        titulo=tit_TF.getText();
    }//GEN-LAST:event_deletar_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO;
    private javax.swing.JButton atualizar_btn;
    private javax.swing.JScrollPane barra_rolagem;
    private javax.swing.JButton deletar_btn;
    private javax.swing.JLabel id_LB;
    private javax.swing.JTextField id_TF;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton salvar_btn;
    private javax.swing.JLabel tit_LB;
    private javax.swing.JTextField tit_TF;
    // End of variables declaration//GEN-END:variables

    @Override
    public void exibe() {
        
        
        initComponents();
        getContentPane().setBackground(Color.BLACK);
        this.setVisible(true);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSerie().setVisible(true);
            }
        });        
        
    }
}
