/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUMain;
import java.io.Console;
import javax.swing.ImageIcon;

/**
 *
 * @author josue
 */
public class formMainTela extends javax.swing.JFrame {

    
    private CDUMain cdumain = null;

    public void setcdu(CDUMain cdumain) {
        this.cdumain = cdumain;
    }

    public void exibe() {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" try catch do Jframe ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMainTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMainTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMainTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMainTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formMainTela().setVisible(true);
        });
        
        String opcao;
        Console c = System.console();
        boolean termina = false;

        System.out.println("POOFlix\n");

        while (!termina) {
            System.out.println("1. Cadastrar Série\n");
            System.out.println("2. Cadastrar Episódio\n");
            System.out.println("3. Cadastrar Personagem\n");
            System.out.println("4. Cadastrar Ator\n");
            System.out.println("5. Sair\n");

            opcao = (String) c.readLine("Digite a opção desejada: ");
            System.out.println(opcao);

            termina = opcao.equals("5");

            if (!termina) {
                cdumain.processaOpcao(opcao);
            }
        }
    }
    /**
     * Creates new form formMainTela
     */
    public formMainTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LB_bemVindo = new javax.swing.JLabel();
        btn_red_icon = new javax.swing.JButton();
        btn_green_icon = new javax.swing.JButton();
        btn_yellow_icon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POOFlix");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 0, 0));
        setName("Tela_FormMain"); // NOI18N
        setPreferredSize(new java.awt.Dimension(810, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LB_bemVindo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LB_bemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_bemVindo.setText("Bem Vindo ao POOflix");
        getContentPane().add(LB_bemVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        btn_red_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/red_icon.png"))); // NOI18N
        btn_red_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_red_iconMouseClicked(evt);
            }
        });
        btn_red_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_red_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_red_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, 150));

        btn_green_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/green_icon.png"))); // NOI18N
        btn_green_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_green_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_green_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 150, 150));

        btn_yellow_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/img/yellow_icon.png"))); // NOI18N
        btn_yellow_icon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yellow_iconActionPerformed(evt);
            }
        });
        getContentPane().add(btn_yellow_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 150, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_yellow_iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yellow_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_yellow_iconActionPerformed

    private void btn_red_iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_red_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_red_iconActionPerformed

    private void btn_green_iconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_green_iconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_green_iconActionPerformed

    private void btn_red_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_red_iconMouseClicked
        // TODO add your handling code here:
        btn_red_icon.setVisible(false);
        btn_green_icon.setVisible(false);
        btn_yellow_icon.setVisible(false);
    }//GEN-LAST:event_btn_red_iconMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_bemVindo;
    private javax.swing.JButton btn_green_icon;
    private javax.swing.JButton btn_red_icon;
    private javax.swing.JButton btn_yellow_icon;
    // End of variables declaration//GEN-END:variables


}
