/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import CDU.CDUcadastrarPf;
import java.awt.Color;

/**
 *
 * @author josue
 */
public class FormPerformance extends javax.swing.JFrame implements Form {

        private int idEp;
        private int idPf;
        private int idAtor;
        private int idPers;
        private CDUcadastrarPf cduPf;

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perf_LB = new javax.swing.JLabel();
        perf_TF = new javax.swing.JTextField();
        ator_LB = new javax.swing.JLabel();
        ator_TF = new javax.swing.JTextField();
        Personagem_LB = new javax.swing.JLabel();
        Person_TF = new javax.swing.JTextField();
        EP_LB = new javax.swing.JLabel();
        ep_TF = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        barra_rolagem = new javax.swing.JScrollPane();
        lista_exibe = new javax.swing.JTable();
        salvar_btn = new javax.swing.JButton();
        atualizar_btn = new javax.swing.JButton();
        deletar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POOFlix - Cadastrando Performances");
        setMinimumSize(new java.awt.Dimension(950, 650));
        setName("FramePerf"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 650));

        perf_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        perf_LB.setForeground(new java.awt.Color(255, 51, 51));
        perf_LB.setText("ID Performance:");

        ator_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ator_LB.setForeground(new java.awt.Color(255, 51, 51));
        ator_LB.setText("ID Ator:");

        ator_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ator_TFActionPerformed(evt);
            }
        });

        Personagem_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Personagem_LB.setForeground(new java.awt.Color(255, 51, 51));
        Personagem_LB.setText("ID Personagem:");

        EP_LB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EP_LB.setForeground(new java.awt.Color(255, 51, 51));
        EP_LB.setText("ID Episodio:");

        Titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 0, 0));
        Titulo.setText("Cadastrando Performances:");

        barra_rolagem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        lista_exibe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Performance", "ID Ator", "ID Personagem"
            }
        ));
        barra_rolagem.setViewportView(lista_exibe);

        salvar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        salvar_btn.setForeground(new java.awt.Color(255, 0, 0));
        salvar_btn.setText("Salvar");
        salvar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_btnActionPerformed(evt);
            }
        });

        atualizar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        atualizar_btn.setForeground(new java.awt.Color(255, 0, 0));
        atualizar_btn.setText("Editar");
        atualizar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizar_btnActionPerformed(evt);
            }
        });

        deletar_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletar_btn.setForeground(new java.awt.Color(255, 0, 0));
        deletar_btn.setText("Deletar");
        deletar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(perf_LB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ator_LB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ator_TF)
                        .addComponent(perf_TF)
                        .addComponent(Person_TF)
                        .addComponent(Personagem_LB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EP_LB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ep_TF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(atualizar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletar_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addGap(261, 261, 261))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(perf_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perf_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EP_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ep_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(ator_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ator_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(Personagem_LB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Person_TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_btn)
                            .addComponent(atualizar_btn)
                            .addComponent(deletar_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(barra_rolagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("telaPerformance");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void ator_TFActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ator_TFActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_ator_TFActionPerformed

        public int getIdEp(){
            return idEp;
        }
        
        public int getIdAtor() {
                return idAtor;
        }

        public int getIdPers() {
                return idPers;
        }

        public int getIdPf() {
                return idPf;
        }
        public void setcdu(CDUcadastrarPf cduPf) {
            this.cduPf = cduPf;
        }
        

        @Override
        public void exibe() {

                initComponents();
                getContentPane().setBackground(Color.BLACK);
                this.setVisible(true);

                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Windows".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(FormPerformance.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(FormPerformance.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(FormPerformance.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(FormPerformance.class.getName()).log(
                                        java.util.logging.Level.SEVERE,
                                        null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new FormPerformance().setVisible(true);
                        }
                });

        }

        private void salvar_btnActionPerformed(java.awt.event.ActionEvent evt) {
                idPf = Integer.parseInt(perf_TF.getText());
                idAtor = Integer.parseInt(ator_TF.getText());
                idPers = Integer.parseInt(Person_TF.getText());
                idEp = Integer.parseInt(ep_TF.getText());

                cduPf.salvarPerformance();
                
        }

        private void deletar_btnActionPerformed(java.awt.event.ActionEvent evt) {
                idPf = Integer.parseInt(perf_TF.getText());
                idAtor = Integer.parseInt(ator_TF.getText());
                idPers = Integer.parseInt(Person_TF.getText());
                idEp = Integer.parseInt(ep_TF.getText());

                cduPf.deletarPerformance();
        }

        private void atualizar_btnActionPerformed(java.awt.event.ActionEvent evt) {
                idPf = Integer.parseInt(perf_TF.getText());
                idAtor = Integer.parseInt(ator_TF.getText());
                idPers = Integer.parseInt(Person_TF.getText());
                idEp = Integer.parseInt(ep_TF.getText());

                cduPf.atualizarPerformance();
        }

        private void listar_btnActionPerformed(java.awt.event.ActionEvent evt) {
                idPf = Integer.parseInt(perf_TF.getText());
                idAtor = Integer.parseInt(ator_TF.getText());
                idPers = Integer.parseInt(Person_TF.getText());
                idEp = Integer.parseInt(ep_TF.getText());

                // cduPf.listarPerformance();
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EP_LB;
    private javax.swing.JTextField Person_TF;
    private javax.swing.JLabel Personagem_LB;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel ator_LB;
    private javax.swing.JTextField ator_TF;
    private javax.swing.JButton atualizar_btn;
    private javax.swing.JScrollPane barra_rolagem;
    private javax.swing.JButton deletar_btn;
    private javax.swing.JTextField ep_TF;
    private javax.swing.JTable lista_exibe;
    private javax.swing.JLabel perf_LB;
    private javax.swing.JTextField perf_TF;
    private javax.swing.JButton salvar_btn;
    // End of variables declaration//GEN-END:variables
}
